//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPOSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Dishes = new HashSet<Dish>();
        }
    
        public string CategoryName { get; set; }
        public decimal VAT { get; set; }
        public decimal ST { get; set; }
        public decimal SC { get; set; }
        public int BackColor { get; set; }
        public int Cat_ID { get; set; }
  }
}
