//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPOSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dish()
        {
            this.Recipes = new HashSet<Recipe>();
            this.RestaurantPOS_OrderedProductBillEB = new HashSet<RestaurantPOS_OrderedProductBillEB>();
            this.RestaurantPOS_OrderedProductBillHD = new HashSet<RestaurantPOS_OrderedProductBillHD>();
            this.RestaurantPOS_OrderedProductBillKOT = new HashSet<RestaurantPOS_OrderedProductBillKOT>();
            this.RestaurantPOS_OrderedProductBillTA = new HashSet<RestaurantPOS_OrderedProductBillTA>();
            this.RestaurantPOS_OrderedProductKOT = new HashSet<RestaurantPOS_OrderedProductKOT>();
            this.Stock_Store_Join = new HashSet<Stock_Store_Join>();
            this.TempRestaurantPOS_OrderedProductKOT = new HashSet<TempRestaurantPOS_OrderedProductKOT>();
            this.Temp_Stock_Store = new HashSet<Temp_Stock_Store>();
        }
    
        public string DishName { get; set; }
        public decimal Rate { get; set; }
        public decimal Discount { get; set; }
        public Nullable<int> BackColor { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Kitchen Kitchen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipe> Recipes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantPOS_OrderedProductBillEB> RestaurantPOS_OrderedProductBillEB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantPOS_OrderedProductBillHD> RestaurantPOS_OrderedProductBillHD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantPOS_OrderedProductBillKOT> RestaurantPOS_OrderedProductBillKOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantPOS_OrderedProductBillTA> RestaurantPOS_OrderedProductBillTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantPOS_OrderedProductKOT> RestaurantPOS_OrderedProductKOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_Store_Join> Stock_Store_Join { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempRestaurantPOS_OrderedProductKOT> TempRestaurantPOS_OrderedProductKOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_Stock_Store> Temp_Stock_Store { get; set; }
    }
}
