//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPOSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public int Id { get; set; }
        public string HotelName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string ContactNo { get; set; }
        public string EmailID { get; set; }
        public string TIN { get; set; }
        public string STNo { get; set; }
        public string CIN { get; set; }
        public byte[] Logo { get; set; }
        public string BaseCurrency { get; set; }
        public string CurrencyCode { get; set; }
        public string TicketFooterMessage { get; set; }
    }
}
