//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPOSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherSetting
    {
        public int ID { get; set; }
        public decimal ParcelCharges { get; set; }
        public decimal HomeDeliveryCharges { get; set; }
        public string CashDrawer { get; set; }
        public decimal VAT { get; set; }
        public decimal ServiceTax { get; set; }
        public decimal ServiceCharges { get; set; }
        public string TA { get; set; }
        public string HD { get; set; }
        public string EB { get; set; }
        public string KG { get; set; }
    }
}
