//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPOSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosGrouping1
    {
        public int id { get; set; }
        public string Col1 { get; set; }
        public Nullable<decimal> Col2 { get; set; }
        public Nullable<int> Col3 { get; set; }
        public Nullable<decimal> Col4 { get; set; }
        public Nullable<decimal> Col5 { get; set; }
        public Nullable<decimal> Col6 { get; set; }
        public Nullable<decimal> Col7 { get; set; }
        public Nullable<decimal> Col8 { get; set; }
        public Nullable<decimal> Col9 { get; set; }
        public Nullable<decimal> Col10 { get; set; }
        public Nullable<decimal> Col11 { get; set; }
        public Nullable<decimal> Col12 { get; set; }
        public Nullable<decimal> Col13 { get; set; }
        public string Col14 { get; set; }
        public Nullable<int> Col15 { get; set; }
    }
}
