//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPOSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe_Join
    {
        public int RJ_ID { get; set; }
        public decimal Quantity { get; set; }
        public string Unit { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
