//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPOSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registration()
        {
            this.Logs = new HashSet<Log>();
            this.RestaurantPOS_BillingInfoEB = new HashSet<RestaurantPOS_BillingInfoEB>();
            this.RestaurantPOS_BillingInfoHD = new HashSet<RestaurantPOS_BillingInfoHD>();
            this.RestaurantPOS_BillingInfoKOT = new HashSet<RestaurantPOS_BillingInfoKOT>();
            this.RestaurantPOS_BillingInfoTA = new HashSet<RestaurantPOS_BillingInfoTA>();
            this.RestaurantPOS_OrderInfoKOT = new HashSet<RestaurantPOS_OrderInfoKOT>();
            this.TempRestaurantPOS_OrderInfoKOT = new HashSet<TempRestaurantPOS_OrderInfoKOT>();
        }
    
        public string UserID { get; set; }
        public string UserType { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string ContactNo { get; set; }
        public string EmailID { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public string Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantPOS_BillingInfoEB> RestaurantPOS_BillingInfoEB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantPOS_BillingInfoHD> RestaurantPOS_BillingInfoHD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantPOS_BillingInfoKOT> RestaurantPOS_BillingInfoKOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantPOS_BillingInfoTA> RestaurantPOS_BillingInfoTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantPOS_OrderInfoKOT> RestaurantPOS_OrderInfoKOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempRestaurantPOS_OrderInfoKOT> TempRestaurantPOS_OrderInfoKOT { get; set; }
    }
}
