//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPOSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantPOS_BillingInfoHD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RestaurantPOS_BillingInfoHD()
        {
            this.RestaurantPOS_OrderedProductBillHD = new HashSet<RestaurantPOS_OrderedProductBillHD>();
        }
    
        public int Id { get; set; }
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public decimal SubTotal { get; set; }
        public decimal HDDiscountPer { get; set; }
        public decimal HomeDeliveryCharges { get; set; }
        public decimal GrandTotal { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public string PaymentMode { get; set; }
        public string BillNote { get; set; }
        public string DiscountReason { get; set; }
        public string Member_ID { get; set; }
    
        public virtual EmployeeRegistration EmployeeRegistration { get; set; }
        public virtual Registration Registration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantPOS_OrderedProductBillHD> RestaurantPOS_OrderedProductBillHD { get; set; }
    }
}
