//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPOSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantPOS_OrderedProductBillTA
    {
        public int OP_ID { get; set; }
        public decimal Rate { get; set; }
        public int Quantity { get; set; }
        public decimal Amount { get; set; }
        public decimal VATPer { get; set; }
        public decimal VATAmount { get; set; }
        public decimal STPer { get; set; }
        public decimal STAmount { get; set; }
        public decimal SCPer { get; set; }
        public decimal SCAmount { get; set; }
        public decimal DiscountPer { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public string Notes { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual RestaurantPOS_BillingInfoTA RestaurantPOS_BillingInfoTA { get; set; }
    }
}
