//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPOSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantPOS_OrderInfoKOT
    {
        public int ID { get; set; }
        public string TicketNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public decimal GrandTotal { get; set; }
        public string GroupName { get; set; }
        public string TicketNote { get; set; }
    
        public virtual R_Table R_Table { get; set; }
        public virtual Registration Registration { get; set; }
    }
}
