//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPOSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Store_Join
    {
        public int SSJ_ID { get; set; }
        public int Qty { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Stock_Store Stock_Store { get; set; }
    }
}
