//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPOSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher_OtherDetails
    {
        public int VD_ID { get; set; }
        public decimal Amount { get; set; }
        public string Note { get; set; }
    
        public virtual Expense Expense { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
