//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPOSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voucher()
        {
            this.Voucher_OtherDetails = new HashSet<Voucher_OtherDetails>();
        }
    
        public int ID { get; set; }
        public string VoucherNo { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public string Details { get; set; }
        public string PaymentMode { get; set; }
        public decimal GrandTotal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher_OtherDetails> Voucher_OtherDetails { get; set; }
    }
}
